lib/eventApp_web/router.ex
defmodule EventAppWeb.Router do
  use EventAppWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug EventApp.Plugs.FetchSession
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", EventAppWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController
    resources "/events", EventController
    resources "/sessions", SessionController,
      only: [:create, :delete], singleton: true
  end

  # Other scopes may use custom stacks.
  # scope "/api", EventAppWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: EventAppWeb.Telemetry
    end
  end
end

lib/eventApp_web/views/layout_view.ex
defmodule EventAppWeb.LayoutView do
  use EventAppWeb, :view
end

lib/eventApp_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en" style="font-size:80%;">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>EventApp · Phoenix Framework</title>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <div role="main" class="container">
      <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
        <p><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
      <% end %>

      <%= if get_flash(@conn, :info) do %>
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <% end %>
      <%= if get_flash(@conn, :error) do %>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <% end %>
      <div class="p-2 d-flex justify-content-between align-content-center bg-dark text-white rounded">
        <h2>Events</h2>
        <div class="d-flex flex-row pt-2">
          <%= if @conn.assigns[:current_user] do %>
            <div class="h5">
              <%= link("Logout", to: Routes.session_path(@conn, :delete), method: :delete) %>
            </div>
          <% else %>
            <div class="col">
              <%= form_for @conn,
              Routes.session_path(@conn, :create),
              [class: "form-inline mb-2"],
              fn f -> %>
                <div class="form-group">
                <%= text_input f, :email, class: "form-control form-control-sm", placeholder: "Email" %>
                <%= submit "Login", class: "btn btn-light mx-2" %>
                </div>
              <% end %>
            </div>
            <%= link "Register", to: Routes.user_path(@conn, :new), class: "btn btn-light mb-2 align-items-center rounded" %>
          <% end %>
        </div>
      </div>

      <%= @inner_content %>

    </div>
  </body>
</html>